### PR TITLE
Full taiko star rating/pp calculation

### LINKED ISSUE #77: Get correct star difficulty on converted maps
On converted maps, it shows the original (std) star difficulty instead of the converted map's (taiko) star difficulty. (because of this, it shows incorrect pp on most converted maps)
For the max combos, use the original one for now. (converted maps does not contain max combos in JSON, causes empty max combo field and NaNpp)

Additionally, normal taiko maps' max combo = circle count but converted maps seem to works differently.

### LINKED ISSUE #88: full taiko support
**Is your feature request related to a problem? Please describe.**
it's currently possible to calculate only pp, not star rating. It means we cannot get star rating for like DT, HT.

**Describe the solution you'd like**
Add complete support for taiko, including HR, DT, HT, EZ

**Additional context**
I'm currently working on it, and it has around 700+ lines of new code for now.
It might take a while to fix bugs.

### LINKED ISSUE #99: Create a type for beatmap data
Referring to this: https://github.com/oamaok/ezpp/blob/main/popup/index.ts#L366

Let's create a type, not a class.

### LINKED ISSUE #103: Bad taiko converter
**Describe the bug**
How am I didn't notice this bug :thinking: (the screenshot was taken on old commit)
image

**To Reproduce**
1. calculate star rating for taiko map

**Expected behavior**
show `5.76`*

**Environment (please complete the following information):**
 - Browser:
   - [x] Chrome
   - [ ] Firefox
 - Version: e13f62fe440269e196291d12aba609ac40ce62de (#93) - latest
 - Beatmap URL:
   - https://osu.ppy.sh/beatmapsets/1378030#taiko/2853012
   - ~~https://osu.ppy.sh/beatmapsets/241526#taiko/557818~~
   - ~~https://osu.ppy.sh/beatmapsets/447342#taiko/960444~~

### PR DESCRIPTION
**Pull request by acrylic-style**
Full taiko support for also conversion maps and a bunch of bug fixes

- Fixes inaccurate star rating for non-conversion maps. the difference between osu! client/website should be acceptable range (around ~0.05 at most)
  - except for aspire map. it's crazy
- Added `util/console.ts` (class Console)
  - Can be used to log only when debugging (not shown on production)
- Implement full taiko support for conversion maps

Resolves #103
Resolves #99
https://github.com/oamaok/ezpp/blob/955101e556fc4f846db49afbe0687e3330984f76/popup/util/pageInfo.ts#L1-L13

Resolves #88
Resolves #77

P.S. maybe consider setting a protected branch rule `Require pull request reviews before merging` if you haven't set it yet

### CODE REVIEW

**Comment by acrylic-style** [comment]
image
It works really fine I guess, but please test before approving it as I might have missed some issues

**Comment by acrylic-style** [comment]
Nevermind, it looks like staminaCheeseDetector.ts isn't working at all

**Review by oamaok — CHANGES_REQUESTED** [review]
overall I think this needs some cleanup, but I think that can be left over once we port anything over to the ezpp calculation package instead. great job!

**Comment by acrylic-style** [comment]
> overall I think this needs some cleanup, but I think that can be left over once we port anything over to the ezpp calculation package instead. great job!

Yeah, it's just a port of osu!lazer source code basically and I wasn't paying attention to code style lol.

**Review by oamaok — APPROVED** [review]

**Pull request merged**
